### ISSUE TITLE
Unit Test of Wrapper Angular Library on ngx-formly fail for one use case

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1756]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```

**Current behavior**

I create wrapper angular library and it extend type for tab, accordion, etc
It has many input filed like model, field, form, **_isJSONSchema_**.
If isJSONSchema is true then it execute the following statement to convert it to FormlyFieldConfig[].

``` this.fields = [this.formlyJsonschema.toFieldConfig(this.jsonSchema)];```

**Expected behavior**

The unit test fail only when I pass **_isJSONSchema_** is true.
I use [Spectator](https://github.com/ngneat/spectator) for unit test.
In my library, FormlyJsonschema is injected and used for converting json to formlyfieldconfig.
I tried Unit Test without mocking as well as mocking but it is not success.

I get the following error
**_TypeError: Cannot read property 'type' of null_**

**Minimal reproduction of the problem with instructions**

**This is my wrapper angular library code.**
```
import { Component, OnInit, Input, EventEmitter, Output } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { FormlyFieldConfig } from '@ngx-formly/core';
import { FormlyJsonschema } from '@ngx-formly/core/json-schema';

@Component({
  selector: 'lib-synapse-primeng-ngxform',
  templateUrl: './synapse-primeng-ngxform.component.html',
  styles: []
})
export class SynapsePrimengNgxformComponent implements OnInit {

  @Input() model: any;
  @Input() jsonSchema: any;
  @Input() isJSONSchema: boolean;
  @Input() formGroup: FormGroup = new FormGroup({});
  fields: FormlyFieldConfig[];
  constructor(private formlyJsonschema: FormlyJsonschema) { }

  ngOnInit() {
    this.setField();
  }
  setField() {
    if (this.isJSONSchema) {
      this.fields = [this.formlyJsonschema.toFieldConfig(this.jsonSchema)];
    }
    else {
      this.fields = this.jsonSchema;
    }
  }
}

```

**This is my unit test using Spectator**

```
describe('SynapsePrimengNgxformComponent', () => {
  let spectator: Spectator<SynapsePrimengNgxformComponent>;
  const createComponent = createComponentFactory({
    declarations: [
      SynapsePrimengNgxformComponent,
      ArrayTypeComponent,
      ObjectTypeComponent,
      FormlyFieldsTab,
      FormlyFieldAccordion
    ],
    component: SynapsePrimengNgxformComponent,
    imports: [
      CommonModule,
      FormsModule,
      PanelModule,
      TabViewModule,
      AccordionModule,
      FormlyPrimeNGModule,
      BrowserModule,
      BrowserAnimationsModule,
      ReactiveFormsModule,
      FormlyModule.forRoot(
        {
          types: formlytypes.types
        }),
    ],
    mocks: [FormlyJsonschema],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
  });
  let formGroup: FormGroup = new FormGroup({});
  let model: any = {};
  let formlyfields: FormlyFieldConfig[] = [
    {
      key: 'name',
      type: 'input',
      templateOptions: {
        label: 'Name (required)',
        required: true,
      },
    },
    {
      key: 'age',
      type: 'input',
      templateOptions: {
        label: 'Age (min= 18, max= 40)',
        type: 'number',
        min: 18,
        max: 40,
        required: true,
      },
    },
  ];
  let jsonfields: any = {
    "title": "A registration form",
    "description": "A simple form example.",
    "type": "object",
    "required": [
      "firstName",
      "lastName"
    ],
    "properties": {
      "firstName": {
        "type": "string",
        "title": "First name",
        "default": "Chuck"
      },
      "lastName": {
        "type": "string",
        "title": "Last name"
      }
    }
  };
  let jsonconverted: any = {
    "type": "object",
    "templateOptions": {
      "label": "A registration form",
      "description": "A simple form example."
    },
    "fieldGroup": [
      {
        "type": "string",
        "defaultValue": "Chuck",
        "templateOptions": {
          "label": "First name",
          "required": true
        },
        "key": "firstName"
      },
      {
        "type": "string",
        "templateOptions": {
          "label": "Last name",
          "required": true
        },
        "key": "lastName"
      }
    ]
  };

  beforeEach(() => {
  });

  it('should create', () => {
    spectator = createComponent({
      // The component inputs
      props: {
        model: model,
        jsonSchema: formlyfields,
        formGroup: formGroup,
        isJSONSchema: false
      },
      // Override the component's providers
      providers: [],
      // Whether to run change detection (defaults to true)
      detectChanges: true
    });
    expect(spectator.component).toBeTruthy();
    expect(spectator.component.fields).toEqual(formlyfields);
  });


  it('setField - isJSONSchema - false', fakeAsync(() => {

    spectator = createComponent({
      // The component inputs
      props: {
        model: model,
        jsonSchema: formlyfields,
        formGroup: formGroup,
        isJSONSchema: false
      },
      // Override the component's providers
      providers: [  ],
      // Whether to run change detection (defaults to true)
      detectChanges: true
    });
    spyOn(spectator.component, 'setField');
    spectator.component.setField();
    expect(spectator.component.fields).toEqual(formlyfields);
  }));


  it('setField - isJSONSchema - true', fakeAsync(() => {

    spectator = createComponent({
      // The component inputs
      props: {
        model: model,
        jsonSchema: jsonfields,
        formGroup: formGroup,
        isJSONSchema: true
      },
      // Override the component's providers
      providers: [],
      // Whether to run change detection (defaults to true)
      detectChanges: true
    });
    //console.log('Fields' + spectator.component.formlyJsonschema);
    console.log('Fields' + spectator.component.isJSONSchema);
    spyOn(spectator.component, 'setField');
    //spectator.component.setField();
    expect(spectator.component.fields).toEqual(jsonconverted);

  }));



});


```

**if I don't mock then following error is coming.**
SynapsePrimengNgxformComponent > setField - isJSONSchema - true
TypeError: Cannot read property 'type' of null

```
error properties: Object({ ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 34523649, rootNodeFlags: 1, nodeMatchedQueries: 0, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 0, flags: 1, childFlags: 34523649, directChildFlags: 34097153, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 7, bindings: [ Object({ flags: 2, ns: '', name: 'ng-untouched', nonMinifiedName: 'ng-untouched', securityContext: undefined, suffix: undefined }), Object({ flags: 2, ns: '', name: 'ng-touched', nonMinifiedName: 'ng-touched', securityContext: undefined, suffix: undefined }), Object({ flags: 2, ns: '', name: 'ng-pristine', nonMinifiedName: 'ng-pristine', securityContext: undefined, suffix: undefined }), Object({ flags: 2, ns: '', name: 'ng-dirty', nonMinifiedName: 'ng-dirty', securityContext: undefined, suffix: undefined }),  ...
    at <Jasmine>
    at FormlyConfig.createComponent (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@ngx-formly/core/fesm2015/ngx-formly-core.js:410:1)
    at CoreExtension.getFieldComponentInstance (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@ngx-formly/core/fesm2015/ngx-formly-core.js:2498:1)
    at CoreExtension.prePopulate (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@ngx-formly/core/fesm2015/ngx-formly-core.js:2342:1)
    at http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@ngx-formly/core/fesm2015/ngx-formly-core.js:591:1
    at <Jasmine>
    at FormlyFormBuilder._buildForm (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@ngx-formly/core/fesm2015/ngx-formly-core.js:587:1)
    at http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@ngx-formly/core/fesm2015/ngx-formly-core.js:602:1
    at <Jasmine>
    at FormlyFormBuilder._buildForm (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@ngx-formly/core/fesm2015/ngx-formly-core.js:598:1)
    at FormlyFormBuilder.buildForm (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@ngx-formly/core/fesm2015/ngx-formly-core.js:579:1)

```

**if I mock I get the following error.**
SynapsePrimengNgxformComponent > setField - isJSONSchema - true
TypeError: this.formlyJsonschema.toFieldConfig is not a function.
```
error properties: Object({ ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 33669121, rootNodeFlags: 33554433, nodeMatchedQueries: 0, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 0, flags: 33554433, childFlags: 114688, directChildFlags: 114688, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 1, bindings: [  ], bindingFlags: 0, outputs: [  ], element: Object({ ns: '', name: 'lib-synapse-primeng-ngxform', attrs: [  ], template: null, componentProvider: Object({ nodeIndex: 1, parent: <circular reference: Object>, renderParent: <circular reference: Object>, bindingIndex: 0, outputIndex: 0, checkIndex: 1, flags: 114688, childFlags: 0, directChildFlags: 0, childMatchedQueries: 0, matchedQueries: Object, matchedQueryIds: 0, references: Object, ngContentIndex: -1, childCount: 0, bindings: Array, bindingFlags: 0 ...
    at <Jasmine>
    at SynapsePrimengNgxformComponent.toFieldConfig [as setField] (http://localhost:9876/_karma_webpack_/webpack:/src/lib/components/ngx-formly/synapse-primeng-ngxform/synapse-primeng-ngxform.component.ts:15:50)
    at SynapsePrimengNgxformComponent.setField (http://localhost:9876/_karma_webpack_/webpack:/src/lib/components/ngx-formly/synapse-primeng-ngxform/synapse-primeng-ngxform.component.ts:11:14)
    at checkAndUpdateDirectiveInline (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:24503:1)
    at checkAndUpdateNodeInline (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35163:1)
    at checkAndUpdateNode (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35102:1)
    at debugCheckAndUpdateNode (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:36124:36)
    at debugCheckDirectivesFn (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:36067:1)
    at Object.eval [as updateDirectives] (ng:///DynamicTestModule/SynapsePrimengNgxformComponent_Host.ngfactory.js:10:5)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:36055:1)
    at checkAndUpdateView (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35067:1)
```

**FormlyJsonschema Mocking code**

```
export class FormlyJsonschemaServiceMock {

  constructor() { }
  jsonconverted: FormlyFieldConfig = {
    "type": "object",
    "templateOptions": {
      "label": "A registration form",
      "description": "A simple form example."
    },
    "fieldGroup": [
      {
        "type": "string",
        "defaultValue": "Chuck",
        "templateOptions": {
          "label": "First name",
          "required": true
        },
        "key": "firstName"
      },
      {
        "type": "string",
        "templateOptions": {
          "label": "Last name",
          "required": true
        },
        "key": "lastName"
      }
    ]
  };
  toFieldConfig(param: any): FormlyFieldConfig {
    return this.jsonconverted;
  }

```

**What is the motivation / use case for changing the behavior?**

The unit test should pass for this use case.

**Please tell us about your environment:**

Windows 10

* **Angular version:** 2.0.X

Angular 8.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
the issue occurs if you passed an empty value to the field:

```ts
this.fields = [null];
```

without a reproduction, we can't help.
