### ISSUE TITLE
Unit Testing ObjectTypeComponent extend type in your sample using Spectator fail 

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1760]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

Unit Test ObjectTypeComponent extend type provided in your sample.

**Expected behavior**

Unit test should pass.

**Minimal reproduction of the problem with instructions**

The object.type.ts extend type is [here ](https://stackblitz.com/angular/akpxxlqedod) in your example.

**What is the motivation / use case for changing the behavior?**

For test coverage, I need to write unit test as given below.

```
describe('ObjectTypeComponent', () => {
  let spectator: Spectator<ObjectTypeComponent>;
  const createComponent = createComponentFactory({
    declarations: [],
    component: ObjectTypeComponent,
    imports: [],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
  });

  beforeEach(() => {
    spectator = createComponent();
  });
  it('should create', () => {
    expect(spectator.component).toBeTruthy();
  });

  it('defaultOptions Initial Value', () => {
    //spectator.detectComponentChanges();
    expect(spectator.component.defaultOptions).toEqual({
      defaultValue: {},
    });

  });

});

```

The following error is comming.
There is no **templateOptions** in the code. I think ngx-formly has that.
Please advise how to overcome this.

```
TypeError: Cannot read property 'templateOptions' of undefined
error properties: Object({ ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 17055745, rootNodeFlags: 16777217, nodeMatchedQueries: 0, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, flags: 16777217, checkIndex: -1, childFlags: 16384, directChildFlags: 16384, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 1, bindings: [  ], bindingFlags: 0, outputs: [  ], element: Object({ ns: null, name: null, attrs: null, template: Object({ factory: Function, nodeFlags: 3, rootNodeFlags: 1, nodeMatchedQueries: 0, flags: 0, nodes: Array, updateDirectives: Function, updateRenderer: Function, handleEvent: Function, bindingCount: 1, outputCount: 0, lastRenderRootNode: Object }), componentProvider: null, componentView: null, componentRendererType: null, publicProviders: null({ NgIf_59: Object }), allProviders: null({ NgIf_59: Object }),  ...
    at <Jasmine>
    at ObjectTypeComponent.get to [as to] (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@ngx-formly/core/fesm2015/ngx-formly-core.js:1436:15)
    at Object.eval [as updateDirectives] (ng:///DynamicTestModule/ObjectTypeComponent.ngfactory.js:41:25)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:36055:1)
    at checkAndUpdateView (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35067:1)
    at callViewAction (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35433:1)
    at execComponentViewsAction (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35361:1)
    at checkAndUpdateView (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35074:1)
    at callWithDebugContext (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:36407:1)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35990:1)
    at ViewRef_.detectChanges (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:23807:1)
```
**Please tell us about your environment:**

Windows 10

* **Angular version:** 2.0.X

Angular 8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
The property `to` is an alias of `field.templateOptions`, the field input is required for a custom field type.

**Comment by Rajanusa** [comment]
Hi Abdellatif Ait boudad,

Thanks for the response.
Unit test we do only with this component right?

I even tried adding **ngIf="to && to.label** to exsiting condition ngIf="to.label" but no luck.

```
import { Component } from '@angular/core';
import { FieldType } from '@ngx-formly/core';

@Component({
  selector: 'formly-object-type',
  template: `
    <legend *ngIf="to && to.label">{{ to.label }}</legend>
    <p *ngIf="to && to.description">{{ to.description }}</p>
    <formly-field *ngFor="let f of field.fieldGroup" [field]="f"></formly-field>
  `,
})
export class ObjectTypeComponent extends FieldType {
  defaultOptions = {
    defaultValue: {},
  };
}

```

**Comment by aitboudad** [comment]
@Rajanusa you'll need to pass a mocked or a valid `field` input value in order to properly unit test your component:

```ts
spectator.setInput('field', {
  ...,
  templateOptions: { ... },
  fieldGroup: [ ... ],
});
```

**Comment by Rajanusa** [comment]
Hi Abdellatif Ait boudad,

Thanks a lot for your input.

As per your suggestion, I passed value to field and others but it gives same error. 
The first error is 
**TypeError: Cannot read property 'templateOptions' of undefined**

It shows the second error, since component is not created, 
**TypeError: Cannot read property 'setInput' of undefined**

```
TypeError: Cannot read property 'templateOptions' of undefined
error properties: Object({ ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 17055745, rootNodeFlags: 16777217, nodeMatchedQueries: 0, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, flags: 16777217, checkIndex: -1, childFlags: 16384, directChildFlags: 16384, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 1, bindings: [  ], bindingFlags: 0, outputs: [  ], element: Object({ ns: null, name: null, attrs: null, template: Object({ factory: Function, nodeFlags: 3, rootNodeFlags: 1, nodeMatchedQueries: 0, flags: 0, nodes: Array, updateDirectives: Function, updateRenderer: Function, handleEvent: Function, bindingCount: 1, outputCount: 0, lastRenderRootNode: Object }), componentProvider: null, componentView: null, componentRendererType: null, publicProviders: null({ NgIf_108: Object }), allProviders: null({ NgIf_108: Object }) ...
    at <Jasmine>
    at ObjectTypeComponent.get to [as to] (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@ngx-formly/core/fesm2015/ngx-formly-core.js:1436:15)
    at Object.eval [as updateDirectives] (ng:///DynamicTestModule/ObjectTypeComponent.ngfactory.js:41:25)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:36055:1)
    at checkAndUpdateView (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35067:1)
    at callViewAction (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35433:1)
    at execComponentViewsAction (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35361:1)
    at checkAndUpdateView (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35074:1)
    at callWithDebugContext (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:36407:1)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35990:1)
    at ViewRef_.detectChanges (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:23807:1)
TypeError: Cannot read property 'setInput' of undefined
    at <Jasmine>
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/lib/components/ngx-formly/components/object.type/object.type.spec.ts:23:15)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/zone.js/dist/zone-evergreen.js:359:1)
    at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/zone.js/dist/zone-testing.js:308:1)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/zone.js/dist/zone-evergreen.js:358:1)
    at Zone.run (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/zone.js/dist/zone-evergreen.js:124:1)
    at runInTestZone (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/zone.js/dist/zone-testing.js:561:1)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/zone.js/dist/zone-testing.js:576:1)
    at <Jasmine>

```

My changed unit test code.

```

describe('ObjectTypeComponent', () => {
  let spectator: Spectator<ObjectTypeComponent>;
  const createComponent = createComponentFactory({
    declarations: [],
    component: ObjectTypeComponent,
    imports: [],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
  });

  beforeEach(() => {
    spectator = createComponent();
  });
  it('should create', () => {
    let formlyFieldConfig: FormlyFieldConfig = { type: 'object', defaultValue: undefined, templateOptions: Object({ label: 'A registration form', readonly: undefined, description: 'A simple form example.' }), fieldGroup: [Object({ type: 'string', defaultValue: 'Chuck', templateOptions: Object({ label: 'First name', readonly: undefined, description: undefined, required: true }), key: 'firstName' }), Object({ type: 'string', defaultValue: undefined, templateOptions: Object({ label: 'Last name', readonly: undefined, description: undefined, required: true }), key: 'lastName' })] };
    spectator.setInput('field',formlyFieldConfig);
    spectator.setInput('to', { label: 'A registration form', readonly: undefined, description: 'A simple form example.' });
    spectator.setInput('model',{});
    spectator.setInput('form',new FormGroup({}));
    expect(spectator.component).toBeTruthy();
  });

});

```

There is no input in the componet since it extends FieldType  it has some filed as below.
but could not see **templateOptions** here. 

```
import { FormGroup } from '@angular/forms';
import { FormlyFieldConfig } from '../components/formly.field.config';
export declare abstract class FieldType<F extends FormlyFieldConfig = FormlyFieldConfig> {
    field: F;
    defaultOptions?: F;
    model: any;
    form: FormGroup;
    options: F['options'];
    readonly key: string;
    readonly formControl: import("@angular/forms").AbstractControl;
    readonly to: import("../components/formly.field.config").FormlyTemplateOptions;
    readonly showError: boolean;
    readonly id: string;
    readonly formState: any;
}
/**
 * @deprecated use `FieldType` instead
 */
export declare abstract class Field extends FieldType {
    constructor();
}


```

Please help  me.

Thanks
Rajan

**Comment by Rajanusa** [comment]
Hi Abdellatif Ait boudad,

Thanks a lot.
I fixed  it by passing parameter when it create as below.

```
   let formlyFieldConfig: FormlyFieldConfig = { type: 'object', defaultValue: undefined, templateOptions: Object({ label: 'A registration form', readonly: undefined, description: 'A simple form example.' }), fieldGroup: [Object({ type: 'string', defaultValue: 'Chuck', templateOptions: Object({ label: 'First name', readonly: undefined, description: undefined, required: true }), key: 'firstName' }), Object({ type: 'string', defaultValue: undefined, templateOptions: Object({ label: 'Last name', readonly: undefined, description: undefined, required: true }), key: 'lastName' })] };

 spectator = createComponent({
      // The component inputs
      props: {
        field: formlyFieldConfig
      },
      // Override the component's providers
      providers: [],
      // Whether to run change detection (defaults to true)
      detectChanges: false 
    });
```
