### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'formControl') in jest test

### ISSUE THREAD

**Issue by wizardnet972** [ngx-formly/ngx-formly#3122]
**Description**
When I run the test I got an error:

```
  ● FooComponent › should create

    TypeError: Cannot read properties of undefined (reading 'formControl')

      at FormlyFooComponent.get formControl [as formControl] (node_modules/@ngx-formly/core/fesm2015/ngx-formly-core.mjs:1208:27)
      at FormlyFooComponent_Template (ng:/FormlyFooComponent.js:34:49)
      at executeTemplate (node_modules/@angular/core/fesm2015/core.mjs:9603:9)
      at refreshView (node_modules/@angular/core/fesm2015/core.mjs:9469:13)
      at refreshComponent (node_modules/@angular/core/fesm2015/core.mjs:10640:13)
      at refreshChildComponents (node_modules/@angular/core/fesm2015/core.mjs:9265:9)
      at refreshView (node_modules/@angular/core/fesm2015/core.mjs:9519:13)
      at renderComponentOrTemplate (node_modules/@angular/core/fesm2015/core.mjs:9583:9)
      at tickRootContext (node_modules/@angular/core/fesm2015/core.mjs:10814:9)
      at detectChangesInRootView (node_modules/@angular/core/fesm2015/core.mjs:10839:5)
      at RootViewRef.detectChanges (node_modules/@angular/core/fesm2015/core.mjs:21411:9)
      at ComponentFixture._tick (node_modules/@angular/core/fesm2015/testing.mjs:140:32)
      at node_modules/@angular/core/fesm2015/testing.mjs:153:22
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:407:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3765:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
      at Object.onInvoke (node_modules/@angular/core/fesm2015/core.mjs:25450:33)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:167:47)
      at NgZone.run (node_modules/@angular/core/fesm2015/core.mjs:25304:28)
      at ComponentFixture.detectChanges (node_modules/@angular/core/fesm2015/testing.mjs:152:25)
      at src/app/foo.component.spec.ts:18:13
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:407:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3765:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:167:47)
      at Object.wrappedFunc (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4250:34)
```

I test the foo component:
```
beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [FormlyFooComponent],
      imports: [FooModule],
    }).compileComponents();
  });

  beforeEach(() => {
    fixture = TestBed.createComponent(FormlyFooComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
```

and the code is very simple:
```
@Component({
  selector: 'foo',
  template: `<div *ngFor="let item of formControl.value">{{ item }}</div>`,
})
export class FormlyFooComponent
  extends FieldType
  implements OnInit, OnDestroy, AfterViewInit
{
  ngOnInit(): void {
    console.log('ngOnInit');
  }
  ngOnDestroy(): void {
    console.log('ngOnDestroy');
  }
  ngAfterViewInit(): void {
    console.log('ngAfterViewInit');
  }
}
```

it seems to access `formControl` and the value is not initial.

**Minimal Reproduction**
```
git clone https://github.com/wizardnet972/ng-formly-test
npm I
npm run test
```

**Your Environment**

- Angular version: ~13.1.0
- Formly version: ^6.0.0-next.6

**Additional context**

**Comment by aitboudad** [comment]
there is a testing package in `v6` which you could use, check the following issue which contains some examples that you can check https://github.com/ngx-formly/ngx-formly/issues/2723#issue-818214519

**Comment by wizardnet972** [comment]
@aitboudad Got it. thanks for your help i appreciate it:)
