### ISSUE TITLE
NOT SUPPORTED: keyword "id", use "$id" for schema ID

### ISSUE THREAD

**Issue by peter-inspire** [ngx-formly/ngx-formly#3191]
**Description**
In a fresh Angular 13 project, installing Formly results in an "An unhandled exception"

**Minimal Reproduction**
Stackblitz template is Angular 10... So anyhow, to see this with current Angular (13.2.3):
```
ng new TryFormly
cd TryFormly
ng add @ngx-formly/schematics --ui-theme=material

```
This yields:
```
✔ Package successfully installed.
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID
See "/tmp/ng-Zh7D0N/angular-errors.log" for further details.
```

**Your Environment**

- Angular version: 13.2.3
- Formly version: @ngx-formly/schematics@5.10.32

**Additional context**
Contents of the above-mentioned install log:
```
[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (/home/peter/formly/TryFormly/node_modules/ajv/dist/vocabularies/core/id.js:6:15)
    at keywordCode (/home/peter/formly/TryFormly/node_modules/ajv/dist/compile/validate/index.js:454:13)
    at /home/peter/formly/TryFormly/node_modules/ajv/dist/compile/validate/index.js:222:17
    at CodeGen.code (/home/peter/formly/TryFormly/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/home/peter/formly/TryFormly/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at iterateKeywords (/home/peter/formly/TryFormly/node_modules/ajv/dist/compile/validate/index.js:219:9)
    at groupKeywords (/home/peter/formly/TryFormly/node_modules/ajv/dist/compile/validate/index.js:208:13)
    at /home/peter/formly/TryFormly/node_modules/ajv/dist/compile/validate/index.js:192:13
    at CodeGen.code (/home/peter/formly/TryFormly/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/home/peter/formly/TryFormly/node_modules/ajv/dist/compile/codegen/index.js:568:18)
```

**Comment by aitboudad** [comment]
I need to update Readme, for Angular 13 you need to use installing with `npm` (https://formly.dev/guide/getting-started) until we release Formly `v6` which fix that issue.

**Comment by aitboudad** [comment]
Added a note in the doc, hope its clear now:
![image](https://user-images.githubusercontent.com/1753742/155030295-c5ea2c62-03b7-4aed-a106-7aea9d3785a6.png)
