### ISSUE TITLE
formly integration with api

### ISSUE THREAD

**Issue by src8na** [ngx-formly/ngx-formly#3540]
src_app_forms_forms_module_ts.js:2 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'key')
TypeError: Cannot read properties of undefined (reading 'key')
    at new FormsComponent (forms.component.ts:48:31)
    at NodeInjectorFactory.FormsComponent_Factory [as factory] (forms.component.ts:39:4)
    at getNodeInjectable (core.mjs:3523:44)
    at instantiateRootComponent (core.mjs:12592:23)
    at createRootComponent (core.mjs:14035:23)
    at ComponentFactory.create (core.mjs:13912:17)
    at ViewContainerRef.createComponent (core.mjs:23230:47)
    at RouterOutlet.activateWith (router.mjs:2569:39)
    at ActivateRoutes.activateRoutes (router.mjs:3003:40)
    at router.mjs:2952:18
    at resolvePromise (zone.js:1211:31)
    at resolvePromise (zone.js:1165:17)
    at zone.js:1278:17
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26261:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)
----------

Getting this error when passing formly fields from api, but when i do the same to display as string in ui is working fine

 <span>key:{{schema1[0].key}}</span> --> working fine
fieldGroup:[
        {
          key:this.schema1[0].key   ---> getting above error
	}]

**Comment by ottomillrath** [comment]
try
`fieldGroup: this.schema1.map((o) => {key: o.key})`

**Comment by src8na** [comment]
> try `fieldGroup: this.schema1.map((o) => {key: o.key})`

I am calling the 0th element of the schema1 array

**Comment by aitboudad** [comment]
Hi, could you please provide a reproduction

Thanks!
