### ISSUE TITLE
Programmatically change of model properties does't affect to repeat-type field controls

### ISSUE THREAD

**Issue by makrom** [ngx-formly/ngx-formly#3581]
**Question**

Hello!
I have a custom repeat-type component and related array property in the model: model.data.doors[].
When the model property was changed another (not formly) component of my app, it does not affected on repeat-type component.
When insert item in model.data.doors[], it is visible but only if repeat-type component is visible on tab-type component at moment. This behavior after adding of this:

<code>
change(event: any): void {
    console.log(event)
    this.rebuildForm();
  }

  rebuildForm() {
    this.builder.buildForm(this.form, this.fields, this.model, this.options);
  }
</code>

When remove item from model.data.doors[], it does not affected at all, but only this error occurred:

<code>
ERROR TypeError: [Formly Error] [Expression "model.door_price"] Cannot read properties of undefined (reading 'door_material_id')
    at model.door_price (/home/roman/proj/erp-client/src/app/order/order.component.ts:3374:62)
    at Object.<anonymous> (/home/roman/proj/erp-client/node_modules/@ngx-formly/core/__ivy_ngcc__/fesm2015/ngx-formly-core.js:2622:1)
    at evalExpression (/home/roman/proj/erp-client/node_modules/@ngx-formly/core/__ivy_ngcc__/fesm2015/ngx-formly-core.js:2453:1)
    at FieldExpressionExtension.checkFieldExpressionChange (/home/roman/proj/erp-client/node_modules/@ngx-formly/core/__ivy_ngcc__/fesm2015/ngx-formly-core.js:2702:1)
    at /home/roman/proj/erp-client/node_modules/@ngx-formly/core/__ivy_ngcc__/fesm2015/ngx-formly-core.js:2675:1
    at Array.forEach (<anonymous>)
    at FieldExpressionExtension._checkField (/home/roman/proj/erp-client/node_modules/@ngx-formly/core/__ivy_ngcc__/fesm2015/ngx-formly-core.js:2667:1)
    at /home/roman/proj/erp-client/node_modules/@ngx-formly/core/__ivy_ngcc__/fesm2015/ngx-formly-core.js:2681:1
    at Array.forEach (<anonymous>)
    at FieldExpressionExtension._checkField (http://localhost:4200/vendor.js:2921:26) {stack: 'TypeError: [Formly Error] [Expression "model.…eld (http://localhost:4200/vendor.js:2921:26)', message: '[Formly Error] [Expression "model.door_price…es of undefined (reading 'door_material_id')'}
</code>

Please, help me to solve this problem.

**Comment by aitboudad** [comment]
Hi,
The question is not clear, please elaborate and provide an example using our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!
