### ISSUE TITLE
The type "select" could not be found. Please make sure that is registered through the FormlyModule declaration

### ISSUE THREAD

**Issue by Scarylaggy** [ngx-formly/ngx-formly#3689]
**Description**
I used an formly example to create a simple form with an select in it. I followed the examples code through stackblitz so no issues appeared during compile time. However the form was not showing and in the console  the following error showed for "select" and later on for type "input"

```
core.mjs:10141 ERROR Error: [Formly Error] The type "select" could not be found. Please make sure that is registered through the FormlyModule declaration.
    at FormlyConfig.getType (ngx-formly-core.mjs:362:23)
    at FormlyField.renderField (ngx-formly-core.mjs:800:51)
    at ngx-formly-core.mjs:860:30
    at observe (ngx-formly-core.mjs:222:9)
    at FormlyField.render (ngx-formly-core.mjs:843:13)
    at FormlyField.triggerHook (ngx-formly-core.mjs:821:18)
    at FormlyField.ngOnChanges (ngx-formly-core.mjs:757:14)
    at FormlyField.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:2812:14)
    at callHookInternal (core.mjs:3804:14)
    at callHook (core.mjs:3835:9)
```

**Minimal Reproduction**
Use the first example for Material design with the current Version of Angular-Material v16

https://stackblitz.com/...

**Your Environment**

- Angular version: 16.0.0
- Formly version: 6.0.0

**Additional context**
My guess is that there was some form of reference change to angular/material so that the basic types cannot be found anymore.

**Comment by aitboudad** [comment]
Make sure `FormlyMaterialModule` is imported:

```patch
import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { ReactiveFormsModule } from '@angular/forms';
import { FormlyModule } from '@ngx-formly/core';
+  import { FormlyMaterialModule } from '@ngx-formly/material';

import { AppComponent } from './app.component';

@NgModule({
  imports: [
    BrowserAnimationsModule,
    ReactiveFormsModule,
+  FormlyMaterialModule,
    FormlyModule.forRoot({
      validationMessages: [{ name: 'required', message: 'This field is required' }],
    }),
  ],
  bootstrap: [AppComponent],
  declarations: [AppComponent],
})
export class AppModule {}
```

**Comment by Scarylaggy** [comment]
You were right, i did miss ne Material Module somehow.
