### ISSUE TITLE
ERROR Error: NG01201: compareWith must be a function, but received undefined

### ISSUE THREAD

**Issue by anuj9196** [ngx-formly/ngx-formly#3765]
**Description**
Using the following schema with two input fields and one select fields.
```typescript
export const boolean = [
  {
    key: "yes",
    type: "input",
    defaultValue: "Yes",
    templateOptions: {
      placeholder: "Label for Yes",
      label: "Label for Yes",
      required: true
    }
  },
  {
    key: "no",
    type: "input",
    defaultValue: "No",
    templateOptions: {
      placeholder: "Label for No",
      label: "Label for No",
      required: true,
    }
  },
  {
    key: "isCorrect",
    type: "select",
    props: [
      {
        label: "Correct Choice",
        options: [
          {label: "Yes", value: "yes"},
          {label: "No", value: "no"}
        ]
      }
    ]
  }
];
```
After adding the `select` type, it gives error in the console
```
ERROR Error: NG01201: compareWith must be a function, but received undefined
    at set compareWith [as compareWith] (forms.mjs:5512:19)
    at writeToDirectiveInput (core.mjs:11846:34)
    at setInputsForProperty (core.mjs:12080:9)
    at elementPropertyInternal (core.mjs:11371:9)
    at ɵɵproperty (core.mjs:15222:9)
    at FormlyFieldSelect_ng_template_0_ng_template_1_Template (ngx-formly-bootstrap-select.mjs:87:38)
    at ReactiveLViewConsumer.runInContext (core.mjs:10414:13)
    at executeTemplate (core.mjs:10954:22)
    at refreshView (core.mjs:12475:13)
    at detectChangesInView (core.mjs:12639:9)
```
In the project's HTML, I can see the following implementation
```html
<ng-template #singleSelect>
        <select
          class="form-select"
          [formControl]="formControl"
          [compareWith]="props.compareWith"                 // <- compareWith presence
          [class.is-invalid]="showError"
          [formlyAttributes]="field"
        >
```

**Minimal Reproduction**

https://stackblitz.com/...

**Your Environment**

- Angular version: 16.1.0
- Formly version: 6.0.0
- Formly Bootstrap: 6.0.0

**Additional context**

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by aitboudad** [comment]
Feel free to leave a comment once you've got a reproduction example, thanks!
