### ISSUE TITLE
Maximum call stack size exceeded with self referencing JSON Schema models

### ISSUE THREAD

**Issue by laurentderu** [ngx-formly/ngx-formly#3989]
**Description**

When using JSON Schema that contains recursive schema references it often happens that we get a "Maximum call stack size exceeded" error

**Minimal Reproduction**

Here is a minimal example to reproduce the problem :

https://stackblitz.com/edit/stackblitz-starters-aag9bp?file=tsconfig.json,src%2Fassets%2Fjson-schema%2Frecurse.json

The condition property of the rule object is a `oneOf` that list all the boolean operation possibles. The `And`, `Or` and `Not` operations contain themselves a predicate property which is also a `oneOf` listing all the boolean operations, hence themselves.

When one click on the add button, a  "Maximum call stack size exceeded" error is thrown.

```
.localservice@runtime.e7ca9335.js:26 ERROR RangeError: Maximum call stack size exceeded
    at FormlyJsonschema._toFieldConfig (vendor.js:90637:17)
    at vendor.js:91082:19
    at Array.map (<anonymous>)
    at FormlyJsonschema.resolveMultiSchema (vendor.js:91081:29)
    at FormlyJsonschema._toFieldConfig (vendor.js:91001:32)
    at vendor.js:90816:28
    at Array.forEach (<anonymous>)
    at FormlyJsonschema._toFieldConfig (vendor.js:90814:48)
    at vendor.js:91082:19
    at Array.map (<anonymous>)
```

**Your Environment**

- Angular version: 16 (but also occurs with Angular 18)
- Formly version: 6.3.7

**Comment by aitboudad** [comment]
At the moment, recursive schema is only supported by array type. for a workarround you may try to change `predicate` to array type https://stackblitz.com/edit/stackblitz-starters-srbe1v?file=src%2Fassets%2Fjson-schema%2Frecurse.json

**Comment by laurentderu** [comment]
Ah I see, thank you. Most of my schemas were using "array" object type and that's why I didn't notice this earlier and assumed `multischema` supported recursive schema.

Converting `Not.predicate` to array solve the issue, but from the user pov the generated form is weird as a Not operand has only one parameter, not a list. And I have several other schema that suffer the same problem.

If this is not on your todo list, maybe I could instead load the sub-schema on demand, e.g. when the user creates a Not predicate I load the model for all the predicates possible but not their sub-schema, and only load them when the user select a given predicate. Is it possible with Formly ?

Alternatively, could you describe how this feature could be added and I will try and make a PR ?

**Comment by OlimjonovOtabek** [comment]
Hi, I opened a PR with a proposed fix for this issue:

https://github.com/ngx-formly/ngx-formly/pull/4179

The fix detects recursive `oneOf` / `anyOf` JSON Schema branches and avoids eagerly expanding them during initial field generation. Recursive branches are built lazily when selected, which prevents the `Maximum call stack size exceeded` error while preserving the existing behavior for non-recursive multischema schemas.

I also added regression coverage for a recursive `oneOf` schema similar to the reported case.
